services:
  backend-compras:
    container_name: backend-compras
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - STOCK_API_URL=http://stock-service:8000/v1
      - LOGISTICS_API_URL=http://shipping_back:3000   # 👈 nombre del contenedor logística
    networks:
      - tpi-network

  frontend-compras:
    container_name: frontend-compras
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    networks:
      - tpi-network
    depends_on:
      - backend-compras

  # ===================== STOCK =====================
  stock:
    container_name: stock-service
    image: fariasvalentino25/docker-stock_backend_api:latest
    ports:
      - "8001:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_HOST: aws-1-us-east-2.pooler.supabase.com
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres.vzabfnzrcynffhdjdddv
      DB_PASSWORD: TNNczJndvipl7Kgk
      KEYCLOAK_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/ds-2025-realm
      KEYCLOAK_AUDIENCE: grupo-13
    networks:
      - tpi-network

  # ===================== LOGISTICA =====================
  shipping_mysql:
    image: mysql:8.0
    container_name: shipping_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: shipping_db
      MYSQL_USER: shipping_user
      MYSQL_PASSWORD: shipping_pass
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "shipping_user", "-pshipping_pass"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - tpi-network

  shipping_back:
    image: ghcr.io/frre-ds/2025-grupo-03-backend-logistica:e1b3782ab13f10c29c20e94eccfa8f1441f9fed7
    container_name: shipping_back
    restart: always
    environment:
      DB_HOST: shipping_mysql
      DB_PORT: 3306
      DB_USERNAME: shipping_user
      DB_PASSWORD: shipping_pass
      DB_DATABASE: shipping_db
    depends_on:
      shipping_mysql:
        condition: service_healthy
    ports:
      - "3010:3010"   
    networks:
      - tpi-network

volumes:
  mysql_data:

networks:
  tpi-network:
    external: true



